# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: z00nx@gmail.com
description: >
  Rambling of a information security enthusiast
baseurl: ""
url: "https://z00nx.github.io"
twitter_username: z00nx
github_username: z00nx

# Build settings
markdown: kramdown
