# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rambling of an infosec enthusiast
email: z00nx(at)gmail.com
description: Rambling of an infosec enthusiast
baseurl: https://z00nx.github.io
url: https://z00nx.github.io
twitter_username: z00nx
github_username: z00nx

# Build settings
markdown: kramdown
